apiVersion: v1
kind: Service
metadata:
  name: app-health-csharp

  labels:
    {{- include "myChart.selectorLabels" . | nindent 4 }}

spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    {{- include "myChart.selectorLabels" . | nindent 4 }}
