name: GitHub Actions Main
on:
 push:
    branches:
    - feature/*
jobs:
  UnitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test
        
  mergeMain:
    name: Merge to Main and Delete
    runs-on: windows-latest
    needs:
      - UnitTests
    steps:
      - name: switch to the main branch
        uses: actions/checkout@v2
        with: 
         fetch-depth: 0
        run: git checkout feature/test123

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature/jaroslav
          delete-branch: true
         


