name: GitHub Actions Main
on: 
  push:
    branches: 
        - feature/*
        - main

jobs:
  UnitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test  
   
  tagged-release:
    runs-on: windows-latest
    needs: 
      - UnitTests
    steps:
    - name: "Build & test"
      run: |
        echo "done!"
    - uses: "gepaplexx/app-health-csharp@latest"
    - name: Release Project
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE.txt
          *.jar   
          
       
  