name: GitHub Actions Main
on: 
  push:
    branches: 
        - feature/*
        - main

jobs:
  UnitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test  
        
  