name: GitHub Actions Main
on: 
  push:
    tags:
       - '*'
    branches: 
       - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  UnitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test  
   
  release:
    name: Release
    runs-on: windows-latest
    needs: 
        - UnitTests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create a new tag
        uses: phish108/autotag-action@1.1.37
        id: autotag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.autotag.outputs.new-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  
          
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./gepaplexxPraktikantenAnwendung
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
  notifyFail:
    name: "Notify Slack Channel #fail"
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - UnitTests
      - release
      - build
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: https://chat.googleapis.com/v1/spaces/AAAAKZ_kPJI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=UxrXeTsszQ2GFfUglk1hH9qZuH_o6zastOP1UF2NDU0%3D
          status: failure
  
