name: GitHub Actions Main
on: 
  push:
    branches: 
        - feature/*
        - main

jobs:
  UnitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test  
   
 
          
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./gepaplexxPraktikantenAnwendung/Dockerfile --tag first-image-name:$(date +%s)
       
  