name: GitHub Actions Main
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unit Test
        run: cd .\app-health-csharp-unitTest && dotnet test  
      - if: ${{ github.app-health-csharp.app-health-csharp-unitTest.conclusion == 'success' }}
        name: testingparty
        run: dir
